### ISSUE TITLE
Investigate effect of NCBI assembly page deprecation

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#147]
We currently rely on NCBI's assembly pages to find the URL for the data files that we pull down in the workflow. The assembly pages will be deprecated in June this year. We need to figure out what the impact will be/whether we need to modify the workflow. 

https://ncbiinsights.ncbi.nlm.nih.gov/2023/03/07/ncbi-datasets-genome-taxonomy-pages/?utm_medium=email&utm_source=govdelivery

@amcooksey could you look into this?

**Comment by amcooksey** [comment]
@mpoelchau I've gone through the documentation and confirmed that all the info we use is still accessible from the new 'datasets genome' pages. I've made a couple of changes to the documentation. We may need to revisit the links in the docs after they discontinue the old assembly pages (I'm not sure if they will change or if they are just different while the two separate pages are coexisting).

**Comment by mpoelchau** [comment]
okay, thanks for investigating @amcooksey !
