### ISSUE TITLE
Workflow: flow_apollo2

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#26]
- Link:
https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/dev/flow_apollo2
https://gitlab.com/i5k_Workspace/apollo2_data_build_scripts

- Link of pre-scripts:

https://github.com/r06942072/apollo2-build-scripts/tree/master/bin

- Goal:
To break the block_build_apollo2 into several single blocks
<br/>

- List:  consist 11 steps in **build_apollo2_flatfiles.sh** 
#41, faToTwoBit
#42, samtools faidx
#43, jbrowse/bin/prepare-refseqs.pl
#44, jbrowse/bin/flatfile-to-json.pl
Doc: http://jbrowse.org/docs/flatfile-to-json.pl.html
#45, jbrowse/bin/generate-names.pl
#46, wiggle-tools/gap2bigwig.py
#47, wiggle-tools/GCcontent2bigwig.py
#48, create symbolic link (ln -s)
#49, jbrowse/bin/add-bw-track_gaps.pl
#50, jbrowse/bin/add-bw-track_gc.pl
#51, add_metadata_to_GC_gap_bigwig_tracks.pl

We can put them all in the same directory, then we don't need to take PATH into consideration.
<br/>

- Mind chart (Edit by Xmind)
![apollo2_workflow](https://user-images.githubusercontent.com/32384566/52283730-070dec00-2931-11e9-801c-2c682671a5bd.PNG)

- cwl viewer
https://view.commonwl.org/workflows/github.com/NAL-i5K/CWL_Common-Workflow-Language/blob/dev/flow_apollo2/apollo2-workflow.cwl

**Comment by r06942072** [comment]
- Take two directories as input in cwl
![apollo2.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/91cff53f-9
171-46fb-84f1-70dffdc4a363)

**Comment by mpoelchau** [comment]
@r06942072 I wonder if it would be better to replace the script build_apollo2_flatfiles.sh with individual cwl blocks for building the Blat database, preparing the reference sequences, etc.

**Comment by r06942072** [comment]
Question to ask : 
- In linux shell script, the path 
JBROWSE_SCRIPTS="/app/data/WebApollo_deployment/nal_jbrowse/bin" https://gitlab.com/i5k_Workspace/apollo2_data_build_scripts/blob/master/build_apollo2_flatfiles.sh

**Comment by r06942072** [comment]
- Connect those tools in this code : **apollo2-workflow.cwl**

- Before
![tree_before.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/8b556a94-af39-4880-8ba1-0a414009f59c)

- After
![tree_after.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/207e23cb-1eae-4a02-ae79-7f6ac7df9288)

**Comment by r06942072** [comment]
- git clone the latest version of jbrowse and then set it up
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/0f9ce307-9b52-43d6-b84c-7524e0084521)

**Comment by r06942072** [comment]
- I tried

**Comment by r06942072** [comment]
For JBrowse installation, let's try two more commands on CentOS: 
http://jbrowse.org/docs/installation.html

**Comment by r06942072** [comment]
- The big picture of apollo2 build script. The result of folder structure without #45 and # 51
That is , already 9 steps connected

![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/37ffb6f7-a3a1-4a12-b8f6-bab92ad47d10)

**Comment by r06942072** [comment]
- Finish! all the 11 steps is connected :)
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/7f6e705e-4ec8-49f0-bc7e-0851da35df53)

**Comment by r06942072** [comment]
- link of cwl viewer
https://view.commonwl.org/workflows/github.com/NAL-i5K/CWL_Common-Workflow-Language/blob/dev/flow_apollo2/apollo2-workflow.cwl

**Comment by r06942072** [comment]
[Bug]
- testdata_varjac
![error_GCcontent.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/dfa379ed-6038-4201-af8c-102e37490547)

![Testcase_error.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/90825bad-2e50-4758-a090-cf9736e57e9a)

**Comment by r06942072** [comment]
[Testcase] Honey bee success 
testdata_apimel

- The folder structure after execution of CWL
![tree result of honey bee.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/5de87d68-b8af-40ad-9ed7-aff51d1dcfd4)

**Comment by mpoelchau** [comment]
@r06942072 can you also add the following steps to this workflow:

- create organism and groups in Apollo2
  - https://gitlab.com/i5k_Workspace/apollo2_web_service_calls/blob/master/createOrganism.py

createOrganism.py may need some tweaking - we can talk about this

**Comment by r06942072** [comment]
[apollo-dev server]
```mkdir /app/data/WebApollo_deployment/apollo2-build-scripts/bin/```
This folder contain the scripts or bin need to use in flow_apollo2
