### ISSUE TITLE
Building Block of Apollo2: prepare-refseqs

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#43]
Link:
https://github.com/r06942072/CWL_Common-Workflow-Language/tree/dev/flow_apollo2

inputs:
**data**
X.fasta
X.fa.fai

outputs:
**seq**
trackList.json
tracks.conf

====================================================
Notice!!
For example,
Set an environment and execute the programs be placed in PATH
Do not take **prepare-refseqs.pl** **JBlibs.pm** into InitialWorkDir in /tmp

**Comment by r06942072** [comment]
- Bug: missing Library
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/5825c4e6-bf03-48ab-98f0-65127ea3bfa4)

**Comment by r06942072** [comment]
- I extract two files from jbrowse, that are **prepare-refseqs.pl** and **JBlibs.pm**
The result after CWL is like the following two screenshot

![apollo2_prepare.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/6e4a58a1-1644-4f51-8496-8ace83d686bb)
<br/>
![apollo2_prepare_tree.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/93a7f8c2-eaa9-4c08-ba42-c9bfea0defb9)

**Comment by r06942072** [comment]
- I modify my cwl file, change the basecommand from ```perl``` to ```prepare-refseq.pl```.
   The result keep the same, and it make it more elegant.


- It basically use the prepare-refseq.pl in home directory ~/bin
![apollo2_prepare_ref.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/325207ff-c143-4ca3-8a8a-6d078e9fd39e)
<br/>

- Success!!!
![PATH.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/539a3619-1fc0-4158-aaad-76579c8e5d6c)
<br/>

**Comment by childers** [comment]
I was able to get the current version of JBrowse set up on my local:

```shell
cchilders@arsmdbe22209001 git-repositories $ git clone https://github.com/GMOD/jbrowse.git
Cloning into 'jbrowse'...
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 89657 (delta 73), reused 96 (delta 48), pack-reused 89489
Receiving objects: 100% (89657/89657), 169.66 MiB | 2.51 MiB/s, done.
Resolving deltas: 100% (53353/53353), done.
cchilders@arsmdbe22209001 git-repositories $ cd jbrowse/
./set	cchilders@arsmdbe22209001 jbrowse (master=) $ ./setup.sh 
Gathering system information ...done.
NOTE: Legacy scripts wig-to-json.pl and bam-to-json.pl have been removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, please use JBrowse 1.12.3 or earlier.
Installing node.js dependencies and building with webpack ...done.
Installing Perl prerequisites ...done.

Formatting Volvox example data ...done.
To see the volvox example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/volvox.

Formatting Yeast example data ...done.
To see the yeast example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/yeast.
cchilders@arsmdbe22209001 jbrowse (master *=) $ 

```
