### ISSUE TITLE
Building Block of Apollo2: flatfile-to-json

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#44]
Link:
https://github.com/r06942072/CWL_Common-Workflow-Language/tree/dev/flow_apollo2

inputs:
X.gff
trackList.json

outputs:
**tracks**
trackList.json

**Comment by r06942072** [comment]
- [Bug] missing gzip.pm
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/e383e8de-4494-4cb0-b9d3-9ed80070472e)

**Comment by mpoelchau** [comment]
- flatfile-to-json.pl will modify trackList.json
- flatfile-to-json.pl will modify the tracks/ directory  - it will create a new directory within tracks/, with the name based on --trackLabel. It might create the tracks/ directory if it doesn't already exist - not sure about this, or if this happens in prepare-refseqs.pl
- perhaps add GENE_MODEL_LABEL to in_tree?

**Comment by r06942072** [comment]
- Ok!! #44 flatfile-to-json would modify trackList.json. Therefore, I should put trackList.json into InitialWorkDirRequirement.

- I am sure that the tracks/ directory is create in #44, not create in #43.

- ??

**Comment by r06942072** [comment]
- I use the --out flag to specify the output location in our folder structure
![flatfile-to-json, add a out flag.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/6817c332-730d-48ab-ac03-8f9135815a0b)

- Tracking the trackList.json file, and it is different form the one in previous block (prepare-refseqs.pl)
![flat-file, diff.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/0ad69a66-07e7-4bda-b60b-ef9e1b4d1c39)

- Success!! But there is one sub-flag not recongized
![flat-file-to-json, success, but --subfeatureclasses not know.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/de8a8ec4-b377-4946-bc81-44842e1135b9)

**Comment by mpoelchau** [comment]
@r06942072 have you tried separating `--getSubfeatures` and `--subfeatureClasses` into 2 separate arguments?

**Comment by r06942072** [comment]
I discard ```--getSubfeatures``` flag, and only keep ```--subfeatureClasses```.

- The cwl file, I only modified the red check mark part
![#44, subfeature flag.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/01d6d9ca-443c-465d-a3fa-5ebfc15d5900)

- The trackList.json file after executing (See red check mark part)
![#44, trackList.json.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/53488cbb-7c4a-4700-9500-8b3ec63994d9)
