### ISSUE TITLE
Building Block of Apollo2: generate-name

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#45]
Link:
https://github.com/r06942072/CWL_Common-Workflow-Language/tree/dev/flow_apollo2

inputs:
None

outputs:
*name*

**Comment by r06942072** [comment]
-[Bug]
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/ec6bfd41-7469-47b0-9e4e-97223fe87212)

**Comment by mpoelchau** [comment]
If you're having perl issues, try using the following code snippet on your local machine (need to have Docker up and running locally):

```
requirements:
  - class: DockerRequirement
    dockerPull: jbrowse/gmod-jbrowse
```

**Comment by mpoelchau** [comment]
- In the inputs list, you *might* have to explicitly invoke the `--tracks` argument, and include a list of all tracks to index (every directory name within the --tracks directory)
- you will probably need to explicitly declare `--out` 
- cwl can capture stderror, right? If so then using the `--verbose` argument would be helpful

**Comment by r06942072** [comment]
If the perl issue is not solved, then we should switch to docker image of jbrowse
On dockerhub:
https://hub.docker.com/search?q=jbrowse&type=image

**Comment by r06942072** [comment]
- manual of generate-name.pl
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/ad7f931c-b334-4311-bf62-5a930bed361b)

**Comment by r06942072** [comment]
- #45 this block take **tracks** as an input, and create **names**
The amount of folders inside **tracks** are not fix, so I should not hard-coded.

**Comment by r06942072** [comment]
[Bug]
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/6d9d2af2-e4 57-4a40-b0ba-aef359f31a6b)
