### ISSUE TITLE
Building Block of Apollo2: gap2bigwig

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#46]
Link:
https://github.com/r06942072/CWL_Common-Workflow-Language/tree/dev/flow_apollo2

inputs:
X.fasta

outputs:
X.fasta.gaps.bigwig

**Comment by r06942072** [comment]
![apollo2_gap2bigwig.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/3b02f643-23cd-4da4-8309-5c833bf5b840)

**Comment by mpoelchau** [comment]
You may need to specify the bigwig tempfile name (`-t`) as an input or argument. You also may need to add it as an output. We don't want to keep the tempfile, but you may have to explicitly tell cwl where the file will be be.

```
Usage: gap2bigwig.py [options]

Options:
  -h, --help            show this help message and exit
  -o BIGWIG_FILENAME, --bigwig_filename=BIGWIG_FILENAME
  -t, --tempfile        
  -k, --keeptemp        
  -g, --gzip            
```

**Comment by mpoelchau** [comment]
Never mind - looks like your command runs fine without using `-t`. Sorry!
