### ISSUE TITLE
Building block: createOrganism.py

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#52]
Ref:
https://gitlab.com/i5k_Workspace/apollo2_web_service_calls/blob/master/createOrganism.py

ADMIN and PASSWD in createOrganism is config in yml file, and keep yml file private

**Comment by r06942072** [comment]
About input arguments, 
is it only matter the "name" of the file , i.e. only take string , not File??

**Comment by mpoelchau** [comment]
Yes, all inputs should be strings.

**Comment by r06942072** [comment]
- Error of not find host!!
![apollo2_createO.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/4774e636-09aa-4009-b029-fcb07a4abae8)

**Comment by r06942072** [comment]
- update createOrganism.py
add two arguments ```username``` and ```password``` into createOrganism.py
link: https://github.com/r06942072/apollo2-build-scripts/blob/master/bin/createOrganism.py

**Comment by r06942072** [comment]
append it after **copy2apollo-dev**
