### ISSUE TITLE
Set up BLAST

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#53]
Set up BLAST
Issue: change those manually mouse clicks on admin page into automatically script.
 
Ref:
https://gitlab.com/i5k_Workspace/workspace_roadmap/wikis/Adding-an-organism-to-the-i5k-Workspace-NAL-version
(Step 6) setup BLAST
https://gitlab.com/i5k_Workspace/workspace_roadmap/issues/759

**Comment by r06942072** [comment]
One possible solution is **web scraping**, but it is without understanding the BLAST backend information, kind of putting the cart before the horse

Ref:
https://youtu.be/vsmxMLmroyQ?t=450

**Comment by r06942072** [comment]
One possible solution is through **web scraping** in frontend.
However, it is a little bit putting the cart before the horse, because it avoids manipulating directly through backend code.

Ref:
https://youtu.be/vsmxMLmroyQ?t=450

**Comment by r06942072** [comment]
【BLAST setup, mouse click flow】
https://gmod-dev.nal.usda.gov/webapp/admin/
- App/Organisms/{Add}, click!!
- Display name/{Laodelphax striatellus}, insert text!!
- {Save}, click!!
- {BLAST}, click!!
- BLAST databases/{Add}, click!!

- {Drop-down list}, click!!
- {Run makeblastdb on selected}, click!!
- checkbox for first Organism, click!!
- Go, Click!!

- {Drop-down list}, click!!
- {Populate Seq in Django}, click!!
- checkbox for first Organism, click!!
- Go, Click!!

- checkbox of "is shown" for fist Organism, click!!
- {Save}, click!!

**Comment by r06942072** [comment]
I tried to install chrome browser on gmod-dev server
![0320_scraping_google_driver.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/0d229d22-e1aa-4993-b243-6078a428697b)

**Comment by r06942072** [comment]
Because gmoed-dev server is CentOS-based
Try rpm not .deb
```yum install google-chrome-stable```

**Comment by mpoelchau** [comment]
@r06942072 you'll need to install that locally (just for your local directory).

**Comment by r06942072** [comment]
David just told us that :
    A while ago, chrome browser had changed some of its library dependencies which aren't compatible for CentOS 6.

Therefore, for web scraping project, my thinking is only do on Firefox browser because this is the CentOS default browser.

**Comment by r06942072** [comment]
![0325_Firefox_PuttyX11.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/3dfec6f7-a151-4982-97d5-2bde23f532cc)

**Comment by r06942072** [comment]
[Bug] Do web scraping on vmware\CentOS6
![image](https://user-images.githubusercontent.com/32384566/55165807-6ffd2d80-5144-11e9-89b1-774d6817f505.png)
