### ISSUE TITLE
extra directories generated in flow_copy2data

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#59]
When running workflow.cwl in flow_copy2data on the Laodelphax example, I get the following output path (probably from genomic_gff.cwl):

`data/other_species/laostr/ASM333518v2/scaffold/analyses/scaffold/analyses/laostr_OGSv1.1`

however, the output path should be 

`data/other_species/laostr/ASM333518v2/scaffold/analyses/laostr_OGSv1.1`

**Comment by r06942072** [comment]
I got the reason why it creates extra directories:
1. I updated in_tree array in example.yml, but I didn't update flow_copy2data/genomic_gff.cwl
2. The in_tree[2] should only be Foldername, for example this case 
in_tree[2] = laostr_OGSv1.1
not in_tree[2] = scaffold/analyses/laostr_OGSv1.1
![image](https://user-images.githubusercontent.com/32384566/55183526-5d93eb80-5166-11e9-9ffa-03113623ba0b.png)

**Comment by r06942072** [comment]
All my update is in a new branch named **dev_0328** created on 28.March
https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/dev_0328
If the result okay, then we can merge to master, otherwise fix it.

Thank you for helping debugging 💯
