### ISSUE TITLE
WorkflowException: Expression evaluation error: No JSON object could be decoded

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#6]
Link: https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/dev/block_test

I created a block_test for demo of parsing the filename inside the initial working directory
I believe that this demo is helpful for achieve my ultimate goal, which is the command "gzip -d *.gz"

I met a bug when I try to use InlineJavascriptRequirement
``
baseCommand: [touch]
``
``
arguments: [$(inputs.dir.listing.[index number].basename)]
``
- **The file structure**
![cwl tree](https://user-images.githubusercontent.com/32384566/47384875-8a833480-d6d6-11e8-8b22-4b9bf3977904.PNG)

- **The error message of cwl-runner** 
![cwl json](https://user-images.githubusercontent.com/32384566/47384926-a8509980-d6d6-11e8-95fe-d020b683c309.PNG)

I do not know how to parse the basename of the file now
basename = 'orange.txt'

**Comment by r06942072** [comment]
expression section
https://www.biostars.org/p/226272/

**Comment by r06942072** [comment]
try Scattering Workflow :)
https://www.commonwl.org/user_guide/23-scatter-workflow/index.html

**Comment by r06942072** [comment]
I change my mind. We need to solve this problem, because it still exist when I try to parse md5checksums.txt from bunch of <.gz>files after block_wget.

Here is the direction to work on :
- Expressions must return a valid JSON data type: one of null, string, number, boolean, array, object.
- https://www.commonwl.org/v1.0/Workflow.html#Expressions

**Comment by r06942072** [comment]
- The message talked about the JSON object structure
![test.cwl.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/d57f14d0-6691-45f8-8bbd-8d8925d77c1e)

- Result
This is my file structure, and after execute cwl-runner.  
We create a file called **apple**
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/512c87c6-dab3-4a25-aac7-963419bea8fd)

**Comment by hsiaoyi0504** [comment]
Have this issue been resolved ?

**Comment by r06942072** [comment]
Yes, it have been resolved.
