### ISSUE TITLE
copy2apollo-dev output needs to be createOrganism input

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#65]
Sometimes, copy2apollo-dev.cwl will run after createOrganism.cwl. However, copy2apollo-dev needs to run beforehand, since files need to be in the right place for createOrganism.cwl to run successfullly. 

We've run into this before - we'll need to think about how a successful copy command should be input to a new process. Alternatively, how to generate the output from previous commands directly into the correct directory. 

If neither of those work, then createOrganism.cwl needs to be removed from finalWorkflow.cwl and run separately.

**Comment by r06942072** [comment]
An example of adding dummy data to confirm the order of excution
See branch ver2
flow_md5checksums/workflow.cwl

**Comment by r06942072** [comment]
BTW, the functionality of copy2apollo-dev is now in **dispatch** in branch ver2

**Comment by r06942072** [comment]
Solution 1 : Dummy data
For example, we want to make sure **setup_folder** -> **2other_species**
Step1. go to setup_folder.cwl, and create a stdout file
Step2. flow_dispatch/2other_species/ catch the dummy data as in_dummy variable

![image](https://user-images.githubusercontent.com/32384566/60911756-e59f8c00-a251-11e9-9a88-a855eb36316b.png)
