### ISSUE TITLE
flow_copy2apollo-dev needs tool for working_files

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#68]
The workflow flow_copy2apollo-dev currently copies blat output and all data files to the correct directories on our servers. However, we need another commandLineTool to copy the files generated in data/working_files to /app/data/working_files

**Comment by r06942072** [comment]
link:
https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/master/flow_copy2apollo-dev

Yes, should add one more commandLineTool file here, so totally 3 commandLineTool
- Is it a good naming??
  - 2other_species.cwl
  - 2working_files.cwl
  - 2blatdb.cwl

**Comment by r06942072** [comment]
See ver2 branch

**Comment by r06942072** [comment]
This function is replaced by **dispatch**
