### ISSUE TITLE
Organism onboarding project

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#69]
**The materials**: 
Organism onboarding repo(i.e. CWL repo) (include setup.sh)
https://github.com/NAL-i5K/Organism_Onboarding
Apollo2 repo 
https://gitlab.com/i5k_Workspace/apollo2_all
Django-webapp repo
https://github.com/NAL-i5K/genomics-workspace

**Getting-started**:
Step1. ```git clone [CWL-project]```
Step2. ```cd [CWL-project]```, run ```./setup.sh``` (linux shell scripts)
Step3. Edit job-[gggsss].yml file
Step4. run ```cwl-runner```

**Comment by r06942072** [comment]
The result after running two organism 
where? on Ubuntu 18.04.

Sorry for my ugly terminal ><"
![0710_2organisms](https://user-images.githubusercontent.com/32384566/60979925-86995000-a301-11e9-87bd-25ce8380f38b.PNG)

**Comment by mpoelchau** [comment]
Closing this - can use other issues to track progress.
