### ISSUE TITLE
Wrapping up my work on Organism Onboarding

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/Organism_Onboarding#71]
- [x] **apollo2_data_processing**

- [x] **dispatch** the output files created in apollo2_data_processing to correct place

- [x] createOrganism

**Comment by r06942072** [comment]
- on apollo-dev  
- ```source /app/data/cwltool/venv/bin/activate```  
- ```cwl-runner final-workflow.cwl job-abcdef.yml```  

- generate-names.cwl

![0731_bug_generate-names](https://user-images.githubusercontent.com/32384566/62298279-b939f280-b440-11e9-9d46-7fc3c2c28e4c.PNG)
![0731_bug2_generate-names](https://user-images.githubusercontent.com/32384566/62298280-b939f280-b440-11e9-9950-325b094f6b3d.PNG)

**Comment by mpoelchau** [comment]
Looks like the data/ directory is not where generate-names.pl expects. You may need to use the full path here: https://github.com/NAL-i5K/Organism_Onboarding/blob/master/flow_apollo2_data_processing/processing/generate-names.cwl#L29
and here: https://github.com/NAL-i5K/Organism_Onboarding/blob/master/flow_apollo2_data_processing/processing/generate-names.cwl#L39

**Comment by r06942072** [comment]
I don't think that the full path needed, because I implemented it in branch **early-dev** before, and it works.  
https://github.com/NAL-i5K/Organism_Onboarding/blob/early-dev/flow_apollo2/generate-names.cwl


I think the reason is that it cannot find folder **tracks/** as input.
