### ISSUE TITLE
apollo2_create_organism needs dispatch output as input

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#82]
The apollo2_create_organism workflow needs to occur after the dispatch workflow, since the apollo application checks whether the jbrowse directory is in the expected path. To make this happen, apollo2_create_organism needs to have an output from the dispatch workflow as input.

**Comment by HsiuKangHuang** [comment]
I added a dummy file as the output of flow dispatch and used it as an input of flow createOrganism.

**Comment by mpoelchau** [comment]
Fixed in #84.
