### ISSUE TITLE
improve createorganism.cwl error handling

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#92]
Currently, createorganism.cwl exits with a success message only if there is error output from the program - not if the organism was actually successfully created. 

One solution is to have the workflow cat the output of the error log after it was generated. Then the user would see whether or not the command failed or succeeded.

**Comment by HsiuKangHuang** [comment]
Okay!
I add a step "cat_createOrganism.log" after the step createOrganism in apolloServer-workflow.cwl.

**Comment by mpoelchau** [comment]
Closed via #90.
