### ISSUE TITLE
Minor fixes to Create symlink workflow

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#98]
There are a few minor fixes needed for the Create symlink workflow
- create a symbolic link from the new assembly folder to 'Current Genome Assembly'
  - e.g. ln -s ephdan-\(Ephemera_danica\)/Edan_2.0/ ephdan-\(Ephemera_danica\)/Current\ Genome\ Assembly
- The gff3 file name in `flow_reorganize_symlinks/analyses_symlink.cwl` needs to come from the yml file - unfortunately the gff3 file name won't always be structured from the genome assembly name. https://github.com/NAL-i5K/Organism_Onboarding/blob/master/flow_reorganize_symlinks/analyses_symlink.cwl#L20

**Comment by HsiuKangHuang** [comment]
For creating a symbolic link to 'Current Genome Assembly', I have one thing to make sure. 
Does it mean I need to create another folder 'Current Genome Assembly' in the step setup_folder.cwl and after the workflow creates all of the symlinks, create a symbolic link to 'Current Genome Assembly'?

**Comment by mpoelchau** [comment]
You shouldn't need to create a folder - just creating the symlink should work.

**Comment by mpoelchau** [comment]
Fixed, closing.
